version: '3.8'

services:
  trending-frontend:
    image: ghcr.io/leduycoder/scientificjournalsystem-trending-fe:latest
    container_name: researchpulse_trending_frontend
    restart: unless-stopped

    ports:
      - "81:80"

    env_file:
      - .env

    networks:
      - researchpulse_network

networks:
  researchpulse_network:
    external: true
    name: researchpulse_network