FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL
ARG VITE_API_CORE_URL
ARG VITE_ARTICLE_GRAPH_ENDPOINT
ARG VITE_PARENT_ORIGIN
ARG VITE_RAG_CHAT_URL
ARG VITE_PAGE_BASE_URL

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_CORE_URL=$VITE_API_CORE_URL
ENV VITE_ARTICLE_GRAPH_ENDPOINT=$VITE_ARTICLE_GRAPH_ENDPOINT
ENV VITE_PARENT_ORIGIN=$VITE_PARENT_ORIGIN
ENV VITE_RAG_CHAT_URL=$VITE_RAG_CHAT_URL
ENV VITE_PAGE_BASE_URL=$VITE_PAGE_BASE_URL

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

